services:
  backend:
    build: ./BackEnd
    env_file:
      - ./BackEnd/.env
    ports:
      - "9999:9999"
    restart: unless-stopped
  
  frontend:
    build: ./FrontEnd
    ports: 
      - "8501:8501"  
    environment:
      - BACKEND_URL=http://backend:9999  
    depends_on: 
      - backend
    restart: unless-stopped
